version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
  
  web: 
    image: example_img
    depends_on: 
      - db  
    ports:
      - '3000':'3000'
    